# Generated by Django 5.1 on 2024-10-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitCounter',
        ),
    ]
