# Generated by Django 5.1 on 2024-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
