# Generated by Django 5.1.1 on 2024-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('milagro', 'Milagro'), ('guayaquil', 'Guayaquil'), ('duran', 'Durán')], max_length=10, null=True),
        ),
    ]
