# Generated by Django 5.1 on 2024-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_movimientoinventario_codigo_pedido_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
